name: Variants test

on: push

env:
  COMPOSE_FILE: docker-compose.test.yml
  APP_NAME: rails_templates
  DOCKER_IMAGE: ${{ github.repository }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  test:
    name: Test ${{ matrix.variant }} variant with rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [web, api]
        ruby: [2.7.1]
        rails: [6.0.0, 6.0.3]
    steps:
      - uses: actions/checkout@v2

      - uses: nimblehq/branch-tag-action@v1.1

      - uses: ruby/setup-ruby@v1.45.0
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Gems cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.rubies/ruby-${{ matrix.ruby }}
          key: use-ruby-${{ runner.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            use-ruby-${{ runner.os }}-${{ matrix.ruby }}-

      - name: Create rails app
        run: |
          gem install rails -v ${{ matrix.rails }} --no-document
          make create OPTIONS="--${{ matrix.variant }}"

      - name: Docker login
        run: echo "$DOCKER_TOKEN" | docker login $DOCKER_REGISTRY --username=$DOCKER_USERNAME --password-stdin

      - name: Docker pull
        run: docker-compose pull test || true
        env:
          BRANCH_TAG: ${{ env.BRANCH_TAG }}-${{ matrix.variant }}-${{ matrix.ruby }}-${{ matrix.rails }}-test

      - name: Docker build
        run: make build
        env:
          BRANCH_TAG: ${{ env.BRANCH_TAG }}-${{ matrix.variant }}-${{ matrix.ruby }}-${{ matrix.rails }}-test

      - name: Test
        run: |
          make test VARIANT=${{ matrix.variant }}
          make run
