name: Variants test

on: push

env:
  COMPOSE_FILE: docker-compose.test.yml
  DOCKER_IMAGE: ${{ github.repository }}
  APP_NAME: rails_app

jobs:
  test:
    name: Test ${{ matrix.variant }} variant with rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [web, api]
        ruby: [2.7.1]
        rails: [6.0.0, 6.0.3]
    steps:
      - uses: actions/checkout@v2

      - uses: nimblehq/branch-tag-action@v1.1

      - uses: ruby/setup-ruby@v1.45.0
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Gems cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.rubies/ruby-${{ matrix.ruby }}
          key: use-ruby-${{ runner.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            use-ruby-${{ runner.os }}-${{ matrix.ruby }}-

      - name: Create rails app
        run: |
          gem install rails -v ${{ matrix.rails }} --no-document
          make create OPTIONS="--${{ matrix.variant }}"

      - name: Docker build
        run: |
          make build

      - name: Test
        run: |
          make test VARIANT=${{ matrix.variant }}
          make run

  build_production:
    name: Build docker production image for ${{ matrix.variant }} variant with rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [web, api]
        ruby: [2.7.1]
        rails: [6.0.0, 6.0.3]
    steps:
      - uses: actions/checkout@v2

      - uses: nimblehq/branch-tag-action@v1.1

      - uses: ruby/setup-ruby@v1.45.0
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Gems cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.rubies/ruby-${{ matrix.ruby }}
          key: use-ruby-${{ runner.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            use-ruby-${{ runner.os }}-${{ matrix.ruby }}-

      - name: Create rails app
        run: |
          gem install rails -v ${{ matrix.rails }} --no-document
          make create OPTIONS="--${{ matrix.variant }}"

      - name: Docker build production image
        run: |
          make build_production
