name: Variants docker build test

on: push

env:
  APP_NAME: rails_templates
  DOCKER_IMAGE: ${{ github.repository }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  RUBY_VERSION: 2.7.1
  RAILS_VERSION: 6.0.3
  NODE_VERSION: 12

jobs:
  build_production:
    name: Build docker production image for ${{ matrix.variant }} variant
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [web, api]
    steps:
      - uses: actions/checkout@v2

      - uses: nimblehq/branch-tag-action@v1.1

      - uses: ruby/setup-ruby@v1.45.0
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Create app folder
        run: mkdir $APP_NAME

      - name: Gems cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.rubies/ruby-${{ env.RUBY_VERSION }}
          key: use-ruby-${{ runner.os }}-${{ env.RUBY_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-use-ruby-${{ env.RUBY_VERSION }}-

      - name: yarn.lock cache
        uses: actions/cache@v2
        with:
          path: ${{ env.APP_NAME }}/yarn.lock
          key: ${{ runner.os }}-yarn-lock-${{ hashFiles('**/package.json*') }}
          restore-keys: |
            ${{ runner.os }}-yarn-lock-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=yarn_cache_dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.yarn_cache_dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: node_modules cache
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.APP_NAME }}/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: Create rails app
        run: |
          gem install rails -v ${{ env.RAILS_VERSION }} --no-document
          make create OPTIONS="--${{ matrix.variant }}"

      - name: Docker login
        run: echo "$DOCKER_TOKEN" | docker login $DOCKER_REGISTRY --username=$DOCKER_USERNAME --password-stdin

      - name: Docker pull
        env:
          BRANCH_TAG: ${{ env.BRANCH_TAG }}-${{ matrix.variant }}
        run: |
          cd $APP_NAME
          docker-compose pull web || true

      - name: Docker build production image
        env:
          BRANCH_TAG: ${{ env.BRANCH_TAG }}-${{ matrix.variant }}
        run: |
          make build_production
          cd $APP_NAME
          docker-compose push web
